### ISSUE TITLE
Refitting consists using cargo subtypes

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD-RC#3765]
**_frosch_ opened the ticket and wrote:**

When refitting a vehicle consist to a certain cargo type and subtype, all refittable vehicles are forced to the same cargo subtype, even if the vehicle does not have any subtypes.

The behaviour does not feel correct, though likely it conforms to TTDP and the specs. Needs further checking...

**Reported version**: _trunk_
**Operating system**: _All_

---

**Comment by TrueBrain** [comment]
Oops, I made an import error :D
